language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: "davidestroveglia"
    token: "ab4c6e57ed0075156d223f13f60e810c7bf2418e" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ant build
  - sonar-scanner